### ISSUE TITLE
Error: Endpoint read failed     at /user_code/node_modules/@google-cloud/logging/node_modules/grpc/src/node/src/client.js:569:15

### ISSUE THREAD

**Issue by deremer** [googleapis/google-cloud-node#2438]
We are using Stack Driver to log errors for Firebase functions. We unpredictably get the error in the title. Typically it happens the first to we try to log an error after a function re-deploys. Subsequent error log writes will go through to StackDriver without issue, but occasionally we'll get the error again.

We're using `"@google-cloud/logging": "^1.0.2",` and deployed via Firebase Functions.

Below is our module that implements the logging...

Anybody have any idea what is causing this?

```javascript
const Logging = require('@google-cloud/logging');

// To keep on top of errors, we should raise a verbose error report with Stackdriver rather
// than simply relying on console.error. This will calculate users affected + send you email
// alerts, if you've opted into receiving them.
const logging = Logging();

// This is the name of the StackDriver log stream that will receive the log
// entry. This name can be any valid log stream name, but must contain "err"
// in order for the error to be picked up by StackDriver Error Reporting.
const logName:string = 'errors-fb-func';

// Enum of StackDriver severities
enum Severities {
  ERROR = 500, // ERROR	(500) Error events are likely to cause problems.
  CRITICAL = 600, // CRITICAL	(600) Critical events cause more severe problems or outages.
  ALERT = 700, // ALERT	(700) A person must take an action immediately.
  EMERGENCY = 800 // EMERGENCY	(800) One or more systems are unusable.
}

// Provide an error object and and optional context object
export function log(err:Error, logLevel:number=Severities.ERROR, user?:string): Promise<any> {
  // https://cloud.google.com/functions/docs/monitoring/error-reporting#advanced_error_reporting

  const FUNCTION_NAME = process.env.FUNCTION_NAME;
  const log = logging.log(logName);

  const metadata = {
    // MonitoredResource
    // See https://cloud.google.com/logging/docs/api/ref_v2beta1/rest/v2beta1/MonitoredResource
    resource: {
      // MonitoredResource.type
      type: 'cloud_function',
      // MonitoredResource.labels
      labels: {
       function_name: FUNCTION_NAME
      }
    },
    severity: logLevel
  };

  const context:any = {};
  if (user && typeof user === 'string') {
    // ErrorEvent.context.user
    context.user = user;
  }

  // ErrorEvent
  // See https://cloud.google.com/error-reporting/reference/rest/v1beta1/ErrorEvent
  let structPayload:any = {
    // ErrorEvent.serviceContext
    serviceContext: {
      // ErrorEvent.serviceContext.service
      service: `cloud_function:${FUNCTION_NAME}`,
      // ErrorEvent.serviceContext.version
      resourceType: 'cloud_function'
    },

  };

  if (context) {
    // ErrorEvent.context
    structPayload.context = context;
  }

  structPayload.message = getMsgForError(err);

  return writeLog(log, metadata, structPayload);
}

function getMsgForError(error:Error): string {
  // https://cloud.google.com/functions/docs/monitoring/error-reporting#advanced_error_reporting
  // ErrorEvent.message
  if (error instanceof Error && typeof error.stack === 'string') {
    return error.stack;
  } else if (typeof error === 'string') {
    return error;
  } else if (typeof error.message === 'string') {
    return error.message;
  } else {
    logFatalError(error, "Error message type not supported");
    return "";
  }
}

function writeLog(log:any, metadata:any, structPayload:any): Promise<any> {
  console.log(metadata);
  console.log(structPayload);
  // Write the error log entry
  return new Promise((resolve, reject) => {
    try {
      log.write(log.entry(metadata, structPayload), (error:any) => {
        if (error) {
          logFatalError(error);
          reject(error);
        }
        resolve();
      });
    } catch(error) {
      reject(error);
    }
  });
}

// Utility function to log error if Logger fails
function logFatalError(error:Error, msg?:string): void {
  console.error(error, msg);
  throw error;
}

// error, crtical, alert, emergency, accept an Error object
// And then set error.stack as the message
export function error(error:Error, user?:string): Promise<any> {
  return log(error, Severities.ERROR, user);
}

export function critical(error:Error, user?:string): Promise<any> {
  return log(error, Severities.CRITICAL, user);
}

export function alert(error:Error, user?:string): Promise<any> {
  return log(error, Severities.ALERT, user);
}

export function emergency(error:Error, user?:string): Promise<any> {
  return log(error, Severities.EMERGENCY, user);
}
```

**Comment by stephenplusplus** [comment]
@ofrobots ever run into anything like this before?

**Comment by deremer** [comment]
As an update, it seems to be more of an issue the first time a call is made to Stackdriver after a Firebase function is updated and restarted. Subsequent requests seem to go through ok. Although it does re-emerge sporadically. We really haven't been able to get to the bottom of it.

Unfortunately, this causes the functions to timeout and throw an "Unhandled Exception", which is not going to work for us in production. So unless we can resolve this issue, we will have to replace Stackdriver with another logger.

**Comment by lukesneeringer** [comment]
I too am hoping @ofrobots will have an idea. :-)

@deremer Can you provide the actual stack trace?

**Comment by deremer** [comment]
Here is one log entry where we see this...

```
{
 insertId:  "000000-6ca1de21-3818-4c66-a620-a8a02227e1a7"   
 labels: {
  execution_id:  "134720017564250"    
 }
 logName:  "projects/hamilton-app-cms-dev/logs/cloudfunctions.googleapis.com%2Fcloud-functions"   
 receiveTimestamp:  "2017-07-10T00:12:20.477133425Z"   
 resource: {
  labels: {
   function_name:  "LotteryActions"     
   project_id:  "hamilton-app-cms-dev"     
   region:  "us-central1"     
  }
  type:  "cloud_function"    
 }
 severity:  "ERROR"   
 textPayload:  "{ Error: Endpoint read failed
    at /user_code/node_modules/@google-cloud/logging/node_modules/grpc/src/node/src/client.js:569:15 code: 14, metadata: Metadata { _internal_repr: {} } } undefined"   
 timestamp:  "2017-07-10T00:12:14.178Z"   
}
```

**Comment by deremer** [comment]
I've been wondering if we're setting metadata incorrectly or something because of the `metadata: Metadata { _internal_repr: {} } } undefined`

But here's another one where it doesn't have that...
```
{
 insertId:  "000001-901cb19e-a4cb-4c78-a339-360408edb7d8"   
 labels: {
  execution_id:  "134720017564250"    
 }
 logName:  "projects/REDACTED/logs/cloudfunctions.googleapis.com%2Fcloud-functions"   
 receiveTimestamp:  "2017-07-10T00:12:20.477133425Z"   
 resource: {
  labels: {
   function_name:  "LotteryActions"     
   project_id:  "REDACTED"     
   region:  "us-central1"     
  }
  type:  "cloud_function"    
 }
 severity:  "ERROR"   
 textPayload:  "Error: Endpoint read failed
    at /user_code/node_modules/@google-cloud/logging/node_modules/grpc/src/node/src/client.js:569:15"   
 timestamp:  "2017-07-10T00:12:14.179Z"   
}
```

**Comment by ofrobots** [comment]
The error indicates a TCP read error – which suggests that sporadically there are some network issues in the environment?

**Comment by ofrobots** [comment]
@swalkowski @jasonpolites: any ideas if this could be an issue on Functions?

**Comment by deremer** [comment]
@ofrobots Just so future readers are 100% clear on this... This code is being run as Firebase Functions, so it's 100% within the Google Cloud environment.

**Comment by murgatroid99** [comment]
Note: the part with the metadata is probably irrelevant. That is trailing response metadata, which is often empty.

**Comment by murgatroid99** [comment]
It seems like the gRPC client successfully establishes a TCP connection (if it didn't, the error would say "Connect failed"), then the first attempt to read from that TCP connection fails for some reason, and the request it was a part of failed.

It might help to see more details of the TCP error, but that doesn't propagate far enough up the stack. It is possible to see it (along with a torrent of other information) by setting the environment variables `GRPC_TRACE=tcp GRPC_VERBOSITY=DEBUG`. The trace information from that gets dumped to stderr, so if you have access to that, that could help (though it could also expose too much information).

**Comment by deremer** [comment]
@murgatroid99 any idea how to set an env var like that with Firebase Functions...or through the Cloud Function console?

Put it in runtime.config.json?

**Comment by murgatroid99** [comment]
I am not familiar with Cloud Functions, but you should just be able to do `process.env.GRPC_TRACE='tcp';` and `process.env.GRPC_VERBOSITY=DEBUG';` in the JS file before loading the logging module.

**Comment by deremer** [comment]
We were experimenting with a few things and one thing we try is moving `const logging = Logging();` inside the `log()` function. Since we've done that we haven't seen the error.

If ok, can we leave this open for a couple of days so that I can report back on if that fixed it or not?

If that is in fact the issue, then Firebase may want to update their docs: https://firebase.google.com/docs/functions/reporting-errors#importing_dependencies

**Comment by deremer** [comment]
Update: since we moved `const logging = Logging();` inside the `log()` function, we have not seen this error.

So I believe we have enough sample data to declare that a fix. Now whether or not that TCP error should in fact happen, is up to you guys to determine :-)

I'm good to close this, but I'll let you guys at Google decide if it should be closed, since you probably want to get the Firebase guys to update their docs (https://firebase.google.com/docs/functions/reporting-errors#importing_dependencies) and their sample (https://github.com/firebase/functions-samples/blob/master/stripe/functions/index.js)

I also logged an issue pointing to this issue for firebase: https://github.com/firebase/functions-samples/issues/194

**Comment by jasonpolites** [comment]
There are some related issues with other GCP node modules related to auth tokens expiring, which fits with the "fix" of moving initialization to function-scope, but does not fit with the "we only see if after re-deploy".  On the other hand, network issues experienced at startup only might be related to slower-than-expected spool up of network resources, but that doesn't fit with the behavior of the "fix".  More investigation on our (Google) end needed methinks.

**Comment by 8357753** [comment]
For me 'Error: "Endpoint read failed"' is often reported in Stackdriver when I call the Spanner API from a GCP Function which has been erroneously deployed with local node_modules from my computer (instead of allowing GCP to create the dependencies).

**Comment by deremer** [comment]
We are deploying via Firebase and accoriding to [this link](https://cloud.google.com/functions/docs/writing/dependencies), "If you are deploying through the Firebase CLI, the local node_modules folder will be ignored, and you must specify your dependencies in package.json"

**Comment by 8357753** [comment]
I get the error occasionally even with the correct deps. Yesterday was especially bad. This morning the error has been replaced with '"Function execution took 242 ms, finished with status: 'connection error'"' and the last log before that is the call to database.runTransaction. I do some more investigation and post the results here

**Comment by 8357753** [comment]
I have issues using GCP Functions and Spanner with JS client 0.7.1. I sometimes receive errors invoking GCP Functions through Postman or using the testing screen from within the GCP Functions web console. The same Function works fine if I invoke it locally during periods when errors are occurring with the remote code. This happens around 5-10% of the time but it is not consistent, sometimes there are periods of no errors. I am initializing the JS client using these instructions "https://cloud.google.com/spanner/docs/getting-started/nodejs/"

The errors are:
database.run
Error: Endpoint read failed\",\"error_code\":14,\"query\":\"SELECT
Error: Session not found: projects/REDACTED/instances/lc-data/databases/lc-data-uat/sessions/AFZejKDAPJhREDACTEDYnFRwi7iMjT0_","error_code":5,"query":"SELECT

database.runTransaction
Error: Endpoint read failed","error_code":14
connection error'"

**Comment by stephenplusplus** [comment]
Thanks to all for explaining their situations in great detail. Please correct any mistakes I might make in my assumptions:

- These problems can be considered the same, in that they are all various forms of a connection error in GCF environments
- The best fixes that the user can do:
  - Move the `@google-cloud/*` module instantiation code to within the function
  - Do not deploy your local `node_modules` directory

@8357753 -- you elaborated on your situation further in #2489, and a few others are involved in a discussion, so we'll pursue the specifics there.

@jasonpolites -- do you still think there needs to be an investigation? Without much experience with GCF, my best interpretation of the situation now is that GCF is doing some type of caching of either old code or stale gRPC connections. If that's the case, I don't think we can solve much from GCN. If that's not the case, any help getting me up to speed on how I might be looking at this wrong would be appreciated. Thanks!

**Comment by cristiano-belloni** [comment]
@stephenplusplus FIY I'm currently experiencing the issue even instantiating within the function and deploying with Firebase. It happens all the time after redeploying
Something like:
```
const pubsub = require('@google-cloud/pubsub')
exports.endpoint = functions.https.onRequest((req, res) => {
  const pubsubClient = pubsub()
  // ...
  pubsubClient .createTopic(name, (err, topic) => {
    topic.publish({ .... })
  }
})
```
Bit of a showstopper :/

**Comment by stephenplusplus** [comment]
cc @lukesneeringer @bjwatson I'm not sure how to proceed on this one.

**Comment by deremer** [comment]
I've also discovered that in our cloud functions write.log() is taking about 15s to log to StackDriver... If I revert to console.error it is almost instantaneous. I've zeroed the delay in precision on to the call of `log.write`. If I print to console just before that line and then just after it is routinely 10-15s.

We thought degraded performance of our functions was related to load, when in fact it seems to just be this method call...

**Comment by ofrobots** [comment]
@deremer: Does the execution of your cloud function completion callback depend upon the settling of the promise returned by your `writeLog` function?

**Comment by deremer** [comment]
@ofrobots generally our functions complete by returning a promise, and occasionally we do return the function `log()` as shown above which in turn returns the promise to write the log.

I should also note that we have since updated the `writeLog` function as shown below because we realized it returns a promise if no callback is provided...

```javascript
function writeLog(syslog:any, metadata:any, structPayload:any): Promise<any> {
  // Write the error log entry
  return syslog.write(syslog.entry(metadata, structPayload));
}
```

**Comment by deremer** [comment]
@ofrobots To clarify more, in our function we were writing to the error log in some situations before continuing on to do other work. Our functions get very high traffic at certain times and we thought the increased latency was just the functions getting overloaded... but it turns out that the increased latency only affected calls that were trying to write to StackDriver...

As mentioned... `log.write()` takes 10-15s every time. So if a function was waiting for the promise to resolve before continuing it was just sitting there waiting.

**Comment by ofrobots** [comment]
@deremer 10-15s to settle the `log.write` promise is unexpected for me. Let me take a look into this.

**Comment by deremer** [comment]
No problem, please let me know if you want more info or to reach out to me directly. I modified our code to use console.error instead of our StackDriver logger and our spike today ran beautifully with nearly all of the latency spike removed... so more evidence that our problem was this log write.

**Comment by ofrobots** [comment]
One more question: Are there any other `log.write` operations in your cloud function? Or the only single write operation happens to be the very last thing that the function does?

**Comment by deremer** [comment]
@ofrobots We wrap `log.write` in the module posted at the top of this issue (note that it has evolved from what is posted, but generally the same).

Throughout our code we do conditionally call Logger.error(error, userId) in some situations. So, yes it is possible that our function may write more than once in a single invocation. As far as I can tell, these always have the latency issue.

I should note that if we call Logger.error, etc. we always `await` it before continuing (we use typescript and webpack)

**Comment by deremer** [comment]
@ofrobots Also, I don't know if the excessive log write time is a different issue or not...happy to move it out to not pollute this issue.

**Comment by ofrobots** [comment]
I do believe it is a different issue. I have split it out here: https://github.com/GoogleCloudPlatform/google-cloud-node/issues/2544.

As for the original issue with tcp timeouts / endpoint read failures: those are due to the fact that cloud functions get aggressively throttled once you call the completion callback. This means that any background work still pending once you call the completion callback is not guaranteed to be able to execute.

The solution is to ensure that you make sure out outstanding work that you care about (e.g. `log.write` as above) is done before you call the completion callback.

**Comment by bjwatson** [comment]
FYI @timburks https://github.com/GoogleCloudPlatform/google-cloud-node/issues/2438#issuecomment-323404472

**Comment by stephenplusplus** [comment]
To all who can help; 

Does anyone have a surefire way to reproduce this issue?

**Comment by stephenplusplus** [comment]
Issue moved to https://github.com/googleapis/nodejs-logging/issues/26

**Comment by stephenplusplus** [comment]
Without a clear path on how to reproduce, I'm stuck on how to resolve. This seems like an issue either with GRPC or the GCF environment. I don't believe there is much we can do from our library.

@lukesneeringer please advise and re-open if necessary.

**Comment by stephenplusplus** [comment]
More reports coming in, let's reopen until we have more certainty we cannot resolve this from our codebase.

**Comment by ChrisBartonLC** [comment]
@stephenplusplus I have pinned to version 0.14.0 of the PubSub client library and this issue does not occur so somewhere between that version and 0.14.5 CloudFunction support has broken. BTW issue #2489 is > 3 months old and PubSub was working a month ago so this may or may not be related.

**Comment by ChrisBartonLC** [comment]
If it helps I can test later versions of the PubSub client, just let me know which you want me to test

**Comment by stephenplusplus** [comment]
> I have pinned to version 0.14.0 of the PubSub client library and the issue described here #2728 does not occur so somewhere between that version and 0.14.5 CloudFunction support has broken. 

@callmehiphop Anything you can think of? I still think this will trace back to the problem that you originally identified @ChrisBartonLC (https://github.com/GoogleCloudPlatform/google-cloud-node/issues/2728#issuecomment-342305105) -- GCF + gRPC can be a problem, which is what this issue is meant to track.

**Comment by callmehiphop** [comment]
Actually yes, there was one PR specifically (https://github.com/GoogleCloudPlatform/google-cloud-node/pull/2627) where we updated the gRPC version from `1.3` to `1.6` and started observing the gRPC channel state when opening streams.

**Comment by bricktownseo** [comment]
In case anyone is waiting to hear back ;) It still is having these issues with cloud functions. When I use the same code but inside of an App Engine instance - no issues.

**Comment by kanagunbr** [comment]
I was able to reproduce the issue enable the grpc debug output. My observation is that, if the channel is idle for 4 minutes, we get the "End Point read Failed". If the idle time is less than 4 min, its not an issue. 

Here is the sequence I tried. 

1. At  18:21:35.292165061 (time), the request to spanner is successful. 
2. At  18:26:44.676780444, I get the "Endpoint read failed" error.  In the GRPC trace, I can see the following. "Socket Closed" error

D1229 18:26:44.677266881    5399 tcp_posix.c:184]            read: error={"created":"@1514597204.677255710","description":"Socket closed","fd":19,"file":"src/core/lib/iomgr/tcp_posix.c","file_line":250,"target_address":"ipv4:74.125.201.95:443"}

3.  Issued another request at 18:27:38.348023815. It is successful at this time. 

4. Waited 3 minutes, and tried another request at 18:30:50.006342607. It is successful as well. 

5. Waited 4 minutes and tried at 18:34:59.179743317. This time, I got the "Endpoint read failed" error. 

6. Tried immediately another request at 18:35:11.271402277, this time it is successful. 

7. Then the request at 18:39:31.524507462. That is after 4 min idle, I got the same error. 



Although I didn't try many times, whatever I tested so far suggests that  somewhere there is a 4 min idle timeout. Not sure, if it is at the spanner server side or at the gRPC side.

**Comment by stephenplusplus** [comment]
Thanks for that information. @murgatroid99 -- what seems like the correct solution, given this pattern described above? Is there a setting we need to change when we instantiate the gRPC client? Or is this something the GCF team needs to handle from their end? Thanks!

**Comment by artemiusgreat** [comment]
Also having this issue with FireStore and PHP client. The first request after ~5 minutes returns an error, the second goes fine.

https://github.com/googlecloudplatform/google-cloud-php#cloud-firestore-beta

```
$store = new FirestoreClient([ 
    'keyFile' => $this->app['firestore.permissions']
]);

$document = $store->document('locks/1');

{
    "message": "OS Error",
    "code": 14,
    "status": "UNAVAILABLE",
    "details": []
}
```

Surprisingly, this method works fine.

`$collection = $store->collection('locks');`

**Comment by stephenplusplus** [comment]
Ping @murgatroid99 -- can you check out https://github.com/GoogleCloudPlatform/google-cloud-node/issues/2438#issuecomment-354795595?

**Comment by murgatroid99** [comment]
I would recommend testing this again with grpc 1.8.4. We changed the status codes of some errors to "UNAVAILABLE", which the Google Cloud libraries retries, and I think this might be one of those errors.

**Comment by vincenzodibiaggio** [comment]
This error also occurs using the `'@google-cloud/datastore'` api. 
Should I open another issue?

**Comment by stephenplusplus** [comment]
For now, we are downgraded to grpc@1.7.x due to another bug: https://github.com/googleapis/gax-nodejs/pull/178

**Comment by stephenplusplus** [comment]
We've just released these modules which include the upgrade to gRPC 1.9. This should correct all problems reported in this issue.

[`@google-cloud/datastore` v1.3.5](https://github.com/googleapis/nodejs-datastore/releases/tag/v1.3.5)
[`@google-cloud/logging` v1.1.7](https://github.com/googleapis/nodejs-logging/releases/tag/v1.1.7)
[`@google-cloud/pubsub` v1.6.5](https://github.com/googleapis/nodejs-pubsub/releases/tag/v1.6.5)
[`@google-cloud/spanner` v1.2.0](https://github.com/googleapis/nodejs-spanner/releases/tag/v1.2.0)

**Comment by gcooney** [comment]
Was seeing this issue using `@google-cloud/monitoring` v0.4.1 to write some metrics via a cloud function.  Tried upgrading to the not yet released 0.5.0 that upgrades to grpc v1.9.1 and I'm seeing a similar but not identical error message.
```
Error: 14 UNAVAILABLE: TCP Read failed
at createStatusError (/user_code/node_modules/@google-cloud/monitoring/node_modules/grpc/src/client.js:64)
at (/user_code/node_modules/@google-cloud/monitoring/node_modules/grpc/src/client.js:583)
```
Is this a different manifestation of the same issue or should I open a new ticket?

**Comment by murgatroid99** [comment]
That is a closely related error. As mentioned, it is now getting reported with the UNAVAILABLE status code. I thought the Google Cloud library would retry requests that fail with that status code.

**Comment by designxtek** [comment]
I'm seeing 
```
{ Error: 14 UNAVAILABLE: TCP Read failed at new createStatusError (/user_code/node_modules/@google-cloud/datastore/node_modules/grpc/src/client.js:64:15) at /user_code/node_modules/@google-cloud/datastore/node_modules/grpc/src/client.js:583:15 code: 14, metadata: Metadata { _internal_repr: {} }, details: 'TCP Read failed' }
```

When trying to save() on datastore via GCF.

**Comment by WaldoJeffers** [comment]
@stephenplusplus Sadly, I'm still seeing this issue. As many people mentioned it, it only happens on the first request. I'm using `@google-cloud/spanner` v1.4.0

The full stack trace is:
```
A  0|app      | Error: Cannot find module '/app/node_modules/@google-cloud/spanner/node_modules/@google-cloud/common-grpc/node_modules/grpc/src/node/src/client.js'
 
A  0|app      |     at Function.Module._resolveFilename (module.js:542:15)
 
A  0|app      |     at Module._load (module.js:472:25)
 
A  0|app      |     at loadAndPatch (/app/node_modules/@google-cloud/trace-agent/build/src/trace-plugin-loader.js:141:36)
 
A  0|app      |     at Function.Module_load [as _load] (/app/node_modules/@google-cloud/trace-agent/build/src/trace-plugin-loader.js:173:37)
 
A  0|app      |     at Module.require (module.js:585:17)
 
A  0|app      |     at require (internal/module.js:11:18)
 
A  0|app      |     at Object.<anonymous> (/app/node_modules/@google-cloud/spanner/node_modules/@google-cloud/common-grpc/src/service.js:26:12)
 
A  0|app      |     at Module._compile (module.js:641:30)
 
A  0|app      |     at Object.Module._extensions..js (module.js:652:10)
 
A  0|app      |     at Module.load (module.js:560:32)
 ```

**Comment by ofrobots** [comment]
@WaldoJeffers based on the error mesage that seems an unrelated error. Can you open a new issue for this?

**Comment by kylehotchkiss** [comment]
Same Issue with `logging-bunyan` package ran from Firebase Functions.

`try-catch` block doesn't appear to catch these either, so if it errors, the function quits.

**Comment by stephenhandley** [comment]
Also seeing an issue with `logging-bunyan` within Firebase Functions
```
Error: 14 UNAVAILABLE: TCP Read failed at Object.exports.createStatusError (/user_code/node_modules/@google-cloud/logging-bunyan/node_modules/grpc/src/common.js:87:15) at Object.onReceiveStatus (/user_code/node_modules/@google-cloud/logging-bunyan/node_modules/grpc/src/client_interceptors.js:1188:28) at InterceptingListener._callNext (/user_code/node_modules/@google-cloud/logging-bunyan/node_modules/grpc/src/client_interceptors.js:564:42) at InterceptingListener.onReceiveStatus (/user_code/node_modules/@google-cloud/logging-bunyan/node_modules/grpc/src/client_interceptors.js:614:8) at callback (/user_code/node_modules/@google-cloud/logging-bunyan/node_modules/grpc/src/client_interceptors.js:841:24)
```

**Comment by victor5114** [comment]
Hello. I'm using @google-cloud/datastore (v1.4.1) to write entities through a stream.
I'm having no issue running the code locally but I get an error when I run the on a cloud function. 

Here's my log trace :
```{
 insertId:  "000000-080c5482-2dd4-4ee6-9227-3f15ae868137"  
 labels: {…}  
 logName:  "xxx"
 receiveTimestamp:  "2018-08-16T16:42:27.680546524Z"  
 resource: {…}  
 severity:  "INFO"  
 textPayload:  "{ Error: 14 UNAVAILABLE: TCP Read failed
    at Object.exports.createStatusError (/srv/node_modules/grpc/src/common.js:87:15)
    at Object.onReceiveStatus (/srv/node_modules/grpc/src/client_interceptors.js:1188:28)
    at InterceptingListener._callNext (/srv/node_modules/grpc/src/client_interceptors.js:564:42)
    at InterceptingListener.onReceiveStatus (/srv/node_modules/grpc/src/client_interceptors.js:614:8)
    at callback (/srv/node_modules/grpc/src/client_interceptors.js:841:24)
  code: 14,
  metadata: Metadata { _internal_repr: {} },
  details: 'TCP Read failed' }"  
 timestamp:  "2018-08-16T16:42:20.211Z"  
}
```

The only difference I can see between the two different environments setup is that I'm passing a credential object required by Google libs to connect to Google Service (Eg. projectId, keyFilename) when I run locally. Nothing is passed on cloud function environment as it's supposed to be implicit Auth across GCP services. (This has been verified with using @google-cloud/storage lib both local and function)

**Comment by JustinBeckwith** [comment]
Well, oh bother.  I can reliably reproduce this.  I have an app engine standard nodejs app that seems to always toss a 500 on my first request.  The output in cloud logging looks like this:

```
A  { Error: 14 UNAVAILABLE: TCP Read failed 
A      at Object.exports.createStatusError (/srv/node_modules/grpc/src/common.js:91:15) 
A      at Object.onReceiveStatus (/srv/node_modules/grpc/src/client_interceptors.js:1204:28) 
A      at InterceptingListener._callNext (/srv/node_modules/grpc/src/client_interceptors.js:568:42) 
A      at InterceptingListener.onReceiveStatus (/srv/node_modules/grpc/src/client_interceptors.js:618:8) 
A      at callback (/srv/node_modules/grpc/src/client_interceptors.js:845:24) 
A    code: 14, 
A    metadata: Metadata { _internal_repr: {} }, 
A    details: 'TCP Read failed' } 
```

This is happening when trying to do a simple read from firestore:
```js
const db = new Firestore();
const jobs = db.collection('jobs');
await jobs.doc(job.id).set(job)
```

After doing a refresh and making the second call, all appears to be working fine.  This does *not* happen locally, or in a docker container.  

@stephenplusplus @alexander-fenster @murgatroid99 @ofrobots

**Comment by jasonpolites** [comment]
Smells a little like an internal networking issue (TCP protocol support surface), which may be unrelated to GRPC or client libraries specifically.  @JustinBeckwith perhaps create an internal bug and reference this issue for context?

**Comment by sergioregueira** [comment]
Same error here using `@google-cloud/logging` (version `4.1.1`) on GAE NodeJS8 Standard Environment.

```
Error: 14 UNAVAILABLE: TCP Read failed 
  at Object.exports.createStatusError (/srv/node_modules/grpc/src/common.js:87:15) 
  at Object.onReceiveStatus (/srv/node_modules/grpc/src/client_interceptors.js:1188:28) 
  at InterceptingListener._callNext (/srv/node_modules/grpc/src/client_interceptors.js:564:42) 
  at InterceptingListener.onReceiveStatus (/srv/node_modules/grpc/src/client_interceptors.js:614:8) 
  at callback (/srv/node_modules/grpc/src/client_interceptors.js:841:24) 
```

First errors detected in three different projects in the first week of December.

**Comment by choipd** [comment]
I've got the same error message in Firebase Functions's log:
```
{ Error: 14 UNAVAILABLE: TCP Read failed
    at Object.exports.createStatusError (/user_code/node_modules/firebase-admin/node_modules/grpc/src/common.js:87:15)
    at Object.onReceiveStatus (/user_code/node_modules/firebase-admin/node_modules/grpc/src/client_interceptors.js:1188:28)
    at InterceptingListener._callNext (/user_code/node_modules/firebase-admin/node_modules/grpc/src/client_interceptors.js:564:42)
    at InterceptingListener.onReceiveStatus (/user_code/node_modules/firebase-admin/node_modules/grpc/src/client_interceptors.js:614:8)
    at callback (/user_code/node_modules/firebase-admin/node_modules/grpc/src/client_interceptors.js:841:24)
  code: 14,
  metadata: Metadata { _internal_repr: {} },
  details: 'TCP Read failed' }
```

**Comment by kyle-mccarthy** [comment]
I am getting this error as well, GAE standard node 10 environment.  I am using `@google-cloud/logging-winston` which is is using `@google-cloud/logging@4.0.1`.

```
Error: 14 UNAVAILABLE: TCP Read failed
    at Object.exports.createStatusError (/srv/node_modules/grpc/src/common.js:87:15)
    at Object.onReceiveStatus (/srv/node_modules/grpc/src/client_interceptors.js:1188:28)
    at InterceptingListener._callNext (/srv/node_modules/grpc/src/client_interceptors.js:564:42)
    at InterceptingListener.onReceiveStatus (/srv/node_modules/grpc/src/client_interceptors.js:614:8)
    at callback (/srv/node_modules/grpc/src/client_interceptors.js:841:24)
```

**Comment by jigneshMitel** [comment]
I'm also facing the same issue where after some idle time, grpc throws UNAVAILABLE error. 
is there a way to work around this problem as I didn't find any solution on this thread.

**Comment by stephenplusplus** [comment]
@JustinBeckwith RE: https://github.com/googleapis/google-cloud-node/issues/2438#issuecomment-450755179 -- have you filed an issue or found anything?

**Comment by JustinBeckwith** [comment]
Yeah, there's an internal bug on cloud functions here.  They're doing some things to increase a timeout, but this issue absolutely still exists.

**Comment by rhodgkins** [comment]
@JustinBeckwith does that also apply to GAE NodeJS8 Standard Environment as well?

**Comment by JustinBeckwith** [comment]
Possibly.  Are you seeing a similar callstack in an app engine standard app?  cc @steren

**Comment by rhodgkins** [comment]
I can't remember/find the stack trace I'm afraid (I starred this issue after this comment
https://github.com/googleapis/google-cloud-node/issues/2438#issuecomment-454587844) :(

I originally came here because of googleapis/nodejs-logging-winston#190, and just reverted back to a previous version of @google-cloud/logging-winston.

**Comment by kyle-mccarthy** [comment]
@JustinBeckwith fwiw I am having this issue in GAE Standard with node 10. Do you know if there is an open issue within google/or their issue tracker?

**Comment by deremer** [comment]
Recently, we've been getting these more in our Node 8 cloud functions. We've isolated it down to a part of the code that writes to Firestore. 

It may be coincidental, but there seems to be a pattern. We tend to get this error in batches (i.e., many of them around the same time and then it stops). It also tends to happen around the time our app's load spikes. I have a hypothesis that during traffic bursts there may be some issue setting up resources as instances our scaled? Just a wild guess...

```
Error: 14 UNAVAILABLE: TCP Read failed
at Object.exports.createStatusError (common.js:87)
at Object.onReceiveStatus (/srv/node_modules/grpc/src/client_interceptors.js:1188)
at InterceptingListener._callNext (/srv/node_modules/grpc/src/client_interceptors.js:564)
at InterceptingListener.onReceiveStatus (/srv/node_modules/grpc/src/client_interceptors.js:614)
at callback (/srv/node_modules/grpc/src/client_interceptors.js:841)
```

**Comment by JustinBeckwith** [comment]
Greetings folks!  I _think_ we've resolved this issue.  With the latest and greatest version of all libraries, you should now be getting a dependency on `@grpc/grpc-js` instead of `grpc`.  This module is rewritten from the ground up, and uses the native HTTP/2 support in node core.  We think the combination of this new module, and some fixes to timeouts on the Cloud Functions/App Engine backend should resolve the issue.

If you *are* running into this still ... please let us know!  Just make sure you're using the latest version of the module, and that you post a stack trace (as above).

**Comment by juanparadox** [comment]
Any work arounds for this issue?

**Comment by JustinBeckwith** [comment]
Not currently, but we're making progress on a fix

**Comment by alexander-fenster** [comment]
Hi folks,

We made some changes in @grpc/grpc-js https://github.com/grpc/grpc-node/pull/1021 that might fix the problem described here. They are releases as v0.5.3. Can I bother you updating, checking if the issue is still here with v0.5.3, and sending the stack trace back if something still does not work?

Thanks!

**Comment by bcoe** [comment]
@deremer :wave: hey, I just wanted to check in and see if @alexander-fenster's changes in `@grpc/grpc-js` helped?

**Comment by deremer** [comment]
> @deremer 👋 hey, I just wanted to check in and see if @alexander-fenster's changes in `@grpc/grpc-js` helped?

We haven’t had a release to deploy with updated dependencies yet. I will report back once we do so and get some data. Lots of other folks on here too so they might see results sooner.

**Comment by bcoe** [comment]
@deremer @juanparadox @kyle-mccarthy, can you folks confirm that the latest release of `@google-cloud/logging` has addressed this issue for you?

**Comment by bcoe** [comment]
@deremer I'm going to go ahead and close this issue, because it's been almost a month, and seems like things have been working okay for folks.

Please feel free to re-open if you are continuing to bump into these issues.

**Comment by felixswift** [comment]
This error popped up this morning for the first time. 

`{ Error: 14 UNAVAILABLE: TCP Read failed
    at Object.exports.createStatusError (/srv/node_modules/grpc/src/common.js:91:15)
    at Object.onReceiveStatus (/srv/node_modules/grpc/src/client_interceptors.js:1204:28)
    at InterceptingListener._callNext (/srv/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/srv/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/srv/node_modules/grpc/src/client_interceptors.js:845:24)
  code: 14,
  metadata: Metadata { _internal_repr: {} },
  details: 'TCP Read failed' }`

**Comment by JustinBeckwith** [comment]
Greetings!  Could you open a new issue with details?
